### Site Settings ###
title               : Christoph Aigner
description         : >-
                      Hi there! ğŸ‘‹ğŸ¼<br>
                      I'm <b>Christoph</b>, an Engineering Leader based in Vienna, Austria ğŸ‡¦ğŸ‡¹
baseurl             : ""
repository          : christophaigner/christophaigner.github.io

### Plugins ###
plugins:
  - jekyll
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji
  - kramdown
  - kramdown-parser-gfm


### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - post_templates/*


### Author Info ###
author:
  name              : Christoph Aigner
  image             : assets/profile.png
  email             : christoph.aigner.work@gmail.com
  github            : christophaigner
  gitlab            : christophaigner
  linkedin          : caigner
  medium            : christophaigner

### Posts ###
permalink: /blog/:title

### Disqus ###
disqus:
  shortname: your-short-name-disqus

# Open the site's URL in the browser.
open_url: true
# Reload a page automatically on the browser when its content is edited.
livereload: true
# Cause a build to fail if there is a YAML syntax error in a page's front matter.
strict_front_matter: true 

### Configure Liquid ###
liquid:
  error_mode: strict
  strict_filters: true

### Analytics ###
analytics:
  enabled: false
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false
  
### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - post_templates/*
